### ISSUE TITLE
thoughts on how to perform actions on resources

### ISSUE THREAD

**Issue by neonstalwart** [interagent/http-api-design#17]
from @joe-mojo https://github.com/interagent/http-api-design/pull/16#issuecomment-45020550

> other role (no update) like sending a message to a resource (handler) or annotating en existing resource.

this raises a point i've been meaning to bring up... using URLs for actions (like /runs/{run_id}/actions/stop) is something that doesn't seem like the most correct thing to do.  would it be more appropriate to recommend using something like JSON-RPC and POST /runs/{run_id} where the JSON-RPC request indicates the action to be performed?

**Comment by geemus** [comment]
I've added a proposed way to work this in https://github.com/interagent/http-api-design/pull/89
