### ISSUE TITLE
Better example for the Resource Names

### ISSUE THREAD

**Issue by keithamus** [interagent/http-api-design#39]
To quote the existing README

> Use the plural version of a resource name unless the resource in question is a singleton within the system (for example, in most systems a given user would only ever have one account). This keeps it consistent in the way you refer to particular resources.

This IMO is a bad example - as a system has many users, which could make the entire example difficult to interpret. Perhaps a clearer example of a singleton API is `/status`, or `/search`.

**Comment by geemus** [comment]
@keithamus hey, sorry about not getting back to us. `/status` could still improve things, any particular reason to close?

**Comment by keithamus** [comment]
Issue is quite old now, I closed it to clean out my [personal issues page](https://github.com/issues). Feel free to re-open if you want to.

**Comment by geemus** [comment]
Thanks for the clarification, better late than never.

**Comment by keithamus** [comment]
Ah sweet! Thanks @geemus. Enjoy the rest of your day :smile:

**Comment by geemus** [comment]
Thanks, you too!

**Comment by crazytonyi** [comment]
What about `/system ` as a singleton? If it refers to the application itself as a resource, there would only be one.  But on that train of thinking, would such a resource be accessible  beyond a GET? It likely wouldn't be something that gets created or deleted. Even a PUT to update it seems semantically dodgy. So OPTIONS for such a resource should only return GET, PATCH. Thoughts?

**Comment by geemus** [comment]
@crazytonyi good question. I suppose that could potentially be another example as there should only be one "self" in the system context. I think the status example works reasonably well for similar reasons (it is, in effect a single property of the system). And it more clearly has updates/etc, though perhaps still not deletes. I dunno, maybe the fact that it is hard for us to think up good examples is an indication that singletons are somewhat of an anti-pattern anyway.
