### ISSUE TITLE
Create a website (Gitpage)

### ISSUE THREAD

**Issue by weblancaster** [interagent/http-api-design#62]
Would be nice to just enabled the Gitpage/website.

Why?
The user want to search/find this resource and read on mobile.

**Comment by geemus** [comment]
Yeah, that is certainly better supported via the git webpage stuff than just in the repo. I'll certainly consider trying to make that change moving forward. Thanks!

**Comment by weblancaster** [comment]
Thanks @geemus

**Comment by geemus** [comment]
I ended up standardizing on gitbook format, which I think/hope achieves much of the same purpose. See:  https://www.gitbook.com/book/geemus/http-api-design/details
