### ISSUE TITLE
Test Framework

### ISSUE THREAD

**Issue by martindale** [interagent/http-api-design#91]
Does there exist any way to test a server for its compliance with the recommendations (and specifications?) within this repository?

**Comment by brandur** [comment]
Hi Eric,

I'm afraid that I personally don't know of such a tool. One problem is that many of the guidelines are fairly high-level and/or abstract. While checking status codes might be feasible, it's more difficult to verify that all IDs conform to UUIDs for example.

I'm closing this out for now, but let us know if you have any other questions/comments.
