### ISSUE TITLE
Json with PLSQL ( PLJSON)

### ISSUE THREAD

**Issue by flgarcia** [interagent/http-api-design#94]
Hello, 
I'm having trouble finding a way to use some PLSON functionality that helps me validate a string and escape characters that do not conform to the following:

any-Unicode-character-
    except-"-or-\-or-
    control-character

I would like something that if in my string find something other than that I substitute for something.

Tks

**Comment by geemus** [comment]
I don't really have any knowledge of PLSQL or PLJSON, perhaps there are other places where you might get a response from someone with a bit more context?
